curl -o ch01.pdf http://infolab.stanford.edu/~ullman/focs/ch01.pdf
curl -o ch02.pdf http://infolab.stanford.edu/~ullman/focs/ch02.pdf
curl -o ch03.pdf http://infolab.stanford.edu/~ullman/focs/ch03.pdf
curl -o ch04.pdf http://infolab.stanford.edu/~ullman/focs/ch04.pdf
curl -o ch05.pdf http://infolab.stanford.edu/~ullman/focs/ch05.pdf
curl -o ch06.pdf http://infolab.stanford.edu/~ullman/focs/ch06.pdf
curl -o ch07.pdf http://infolab.stanford.edu/~ullman/focs/ch07.pdf
curl -o ch08.pdf http://infolab.stanford.edu/~ullman/focs/ch08.pdf
curl -o ch09.pdf http://infolab.stanford.edu/~ullman/focs/ch09.pdf
curl -o ch10.pdf http://infolab.stanford.edu/~ullman/focs/ch10.pdf
curl -o ch11.pdf http://infolab.stanford.edu/~ullman/focs/ch11.pdf
curl -o ch12.pdf http://infolab.stanford.edu/~ullman/focs/ch12.pdf
curl -o ch13.pdf http://infolab.stanford.edu/~ullman/focs/ch13.pdf
curl -o ch14.pdf http://infolab.stanford.edu/~ullman/focs/ch14.pdf
